language: node_js
cache:
  directories:
  - node_modules
node_js:
- stable
install:
- npm install
script:
- npm run lint
- npm run semantic-release
after_success:
- make deploy
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
